### ISSUE TITLE
DeprecationWarning: concurrency_count has been deprecated

### ISSUE THREAD

**Issue by merolaika** [XpycT/MagicPrompt#2]
py MagicPrompt.py
Traceback (most recent call last):
  File "Y:\MyJobs\MagicPrompt\MagicPrompt.py", line 190, in <module>
    magicprompt.queue(concurrency_count=20).launch(server_name="0.0.0.0", server_port=8090, show_api=False, debug=True)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\site-packages\gradio\blocks.py", line 1766, in queue
    raise DeprecationWarning(
DeprecationWarning: concurrency_count has been deprecated. Set the concurrency_limit directly on event listeners e.g. btn.click(fn, ..., concurrency_limit=10) or gr.Interface(concurrency_limit=10). If necessary, the total number of workers can be configured via `max_threads` in launch().

**Comment by JerryZhuu** [comment]
you can change "queue(concurrency_count=20)." into "queue()"
